### ISSUE TITLE
Awesome project!

### ISSUE THREAD

**Issue by CTanguay-Sabourin** [mtl-brainhack-school-2019/kongnorman_BrainDecoding#6]
Hi Norman, 
I would be very interested in helping you in your projects if you want some opinions/helps! I just started MRI-neuroimaging and the ML applications only a couple of months ago and I still feel in the same boat.

Excited to see what your project will look like!

Christophe Tanguay-Sabourin

**Comment by kongnorman** [comment]
Thanks! Let's keep in touch. Hopefully we can help each other!
